#!/usr/bin/env python3
"""Math: how do we get to 1,000 real opportunities?"""

print("=== THE FUNNEL (from today's data) ===")
print()
print("SCP cache: 1,334 players, 4,861 unique cards, 66,079 variants")
print("We search: 60 players (4.5% of players)")
print("We searched: 2,889 variations (4.4% of variants)")
print("eBay had results: 511 queries (17.7% hit rate)")
print("Total listings found: 7,226")
print("Matched to card identity: 2,723")
print("Passed H4 filters: ~916")
print("Real opportunities: ~108")
print()

print("=== KEY RATIO: 108 real from 2,889 searches = 1 real per 26.7 searches ===")
print()

print("=== OPTION A: More API calls (Compatible App) ===")
print("50,000 calls/day -> ~24,000 searches (after auction budget)")
print("24,000 / 26.7 = ~899 real opportunities per run")
print("2 runs/day with cache = ~899 first run + ~200 new on second = ~1,099")
print("VERDICT: Gets us there. Waiting on approval.")
print()

print("=== OPTION B: Accumulate over days ===")
print("Current pipeline DELETES old BIN opps each run (shard_players scope)")
print("If we KEEP non-expired opportunities across runs:")
print("  Day 1: ~108 real")
print("  Day 2: ~108 but maybe 40% overlap with day 1 = ~65 new")
print("  Day 7: ~108 + (6 * 65) = ~498")
print("  Day 14: ~108 + (13 * 65) = ~953")
print("REQUIRES: stop deleting old opps, add expiry logic instead")
print("VERDICT: Slow but works. 2 weeks to 1,000.")
print()

print("=== OPTION C: Better search targeting (same API budget) ===")
print("Problem: 82.3% of searches return 0 results (wasted API calls)")
print("2,889 searches but only 511 had results")
print("If we could predict which searches will have results:")
print("  2,400 searches * 80% hit rate = 1,920 with results")
print("  1,920 / (511/108) = ~406 real opps per run")
print("HOW: search popular cards first (high eBay listing count)")
print("  - Cards that had results last run -> search again (cache tells us)")
print("  - Cards with sold_comps -> active market, likely has listings")
print("  - Skip obscure parallels with no eBay presence")
print("VERDICT: Could 3-4x our yield with same API budget.")
print()

print("=== OPTION D: Auction pipeline (untapped) ===")
print("Auction pipeline runs separately, different queries")
print("Currently ~30 opps/run, accuracy unknown with H4")
print("Auctions are where margins live (your words)")
print("If auction accuracy is similar: ~30 * 11.8% = ~3.5 real per run")
print("BUT auction pipeline searches differently (value queries, not per-variation)")
print("It may find opportunities BIN pipeline misses entirely")
print("VERDICT: Additive. Need to measure.")
print()

print("=== OPTION E: All of the above ===")
print("Short term (this week):")
print("  - Stop deleting old opps (accumulate) -> grows daily")
print("  - Prioritize searches by hit rate (Option C) -> 3-4x yield")
print("  - Measure auction pipeline accuracy -> additive opps")
print("  - Apply for Compatible App -> 10x when approved")
print()
print("Medium term (next 2 weeks):")
print("  - Compatible App approved -> search all 66K variants")
print("  - Accumulation + higher yield = 1,000+ real opps")
print("  - CE + 130point validation separates real from false")
print()

print("=== WHAT TO BUILD RIGHT NOW ===")
print("1. Stop deleting old opps -- add created_at expiry instead of DELETE")
print("2. Prioritize searches: use cache hit history to search productive variations first")
print("3. Measure auction pipeline with H4 filters")
print("4. Wire CE + 130point as post-pipeline validation")
